### ISSUE TITLE
pycharm运行，邀请成功但是很多红字报错

### ISSUE THREAD

**Issue by ZeroDim** [LinYuanovo/pikpak_auto_invite#23]
=========正在邀请第 1 个邀请码=========
验证滑块中...
验证通过!!!
获取邮箱验证码:979472
邀请码:******==> 邀请成功, 用时: 8.16 秒
邮箱: qq78h3aqnh@vafyxh.com
密码: linyuan666
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000233E95049D0>
Traceback (most recent call last):
  File "D:\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Python\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "D:\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000233E95049D0>
Traceback (most recent call last):
  File "D:\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Python\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "D:\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000233E95049D0>
Traceback (most recent call last):
  File "D:\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Python\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "D:\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000233E95049D0>
Traceback (most recent call last):
  File "D:\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Python\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "D:\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000233E95049D0>
Traceback (most recent call last):
  File "D:\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Python\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "D:\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000233E95049D0>
Traceback (most recent call last):
  File "D:\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Python\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "D:\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by ghostWindows-files** [comment]
成功邀请了就行，管他那么多呢b(￣▽￣)d

**Comment by LinYuanovo** [comment]
能运行就不管，没啥大问题这个
